name: PyMaxflow deployment

on:
  push:
    tags: 'v[0-9]+*'

jobs:
  deploy-sdist:
    name: Deploy source distribution
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build sdist
        run: python -m build --sdist
      - name: Deploy sdist
        run: |
          python3 -m pip install twine
          python3 -m twine upload --skip-existing dist/*

  deploy-wheels:
    name: Deploy wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ARCHS: "auto64"
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_SKIP: "*musllinux* pp*-win* pp*-macosx* pp*"
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
      - name: Deploy
        run: |
          python3 -m pip install twine
          python3 -m twine upload --skip-existing wheelhouse/*.whl
